# Simplified Docker Compose for MissionMind TasksMind Core Services
version: '3.8'

services:
  # Database services
  postgres-tasks:
    image: postgres:15
    environment:
      POSTGRES_DB: tasksmind_tasks
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass123
    volumes:
      - postgres_tasks_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d tasksmind_tasks"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-assignments:
    image: postgres:15
    environment:
      POSTGRES_DB: tasksmind_assignments
      POSTGRES_USER: assignuser
      POSTGRES_PASSWORD: assignpass123
    volumes:
      - postgres_assignments_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U assignuser -d tasksmind_assignments"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-comments:
    image: postgres:15
    environment:
      POSTGRES_DB: tasksmind_comments
      POSTGRES_USER: commentuser
      POSTGRES_PASSWORD: commentpass123
    volumes:
      - postgres_comments_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U commentuser -d tasksmind_comments"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Core microservices
  task-service:
    build:
      context: ./services/task-service
    environment:
      DATABASE_URL: postgresql://taskuser:taskpass123@postgres-tasks:5432/tasksmind_tasks
      SERVICE_PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      postgres-tasks:
        condition: service_healthy
    restart: unless-stopped

  assignment-service:
    build:
      context: ./services/assignment-service
    environment:
      DATABASE_URL: postgresql://assignuser:assignpass123@postgres-assignments:5432/tasksmind_assignments
      SERVICE_PORT: 8004
      TASK_SERVICE_URL: http://task-service:8001
      USER_SERVICE_URL: http://user-service:8002
    ports:
      - "8004:8004"
    depends_on:
      postgres-assignments:
        condition: service_healthy
      task-service:
        condition: service_started
    restart: unless-stopped

  comment-service:
    build:
      context: ./services/comment-service
    environment:
      DATABASE_URL: postgresql://commentuser:commentpass123@postgres-comments:5432/tasksmind_comments
      SERVICE_PORT: 8005
    ports:
      - "8005:8005"
    depends_on:
      postgres-comments:
        condition: service_healthy
    restart: unless-stopped

  api-gateway:
    build:
      context: ./services/api-gateway
    environment:
      GATEWAY_PORT: 8000
      TASK_SERVICE_URL: http://task-service:8001
      ASSIGNMENT_SERVICE_URL: http://assignment-service:8004
      COMMENT_SERVICE_URL: http://comment-service:8005
    ports:
      - "8000:8000"
    depends_on:
      - task-service
      - assignment-service
      - comment-service
    restart: unless-stopped

volumes:
  postgres_tasks_data:
  postgres_assignments_data:
  postgres_comments_data:

networks:
  default:
    driver: bridge